// Tesla Delivery Hub v10 ??? New tab approach
(function(){
  // Get auth
  var tk=(localStorage.getItem('delops_id_token')||'').replace(/^"|"$/g,'');
  var t2=(localStorage.getItem('delops_id_token_data')||'').replace(/^"|"$/g,'');
  var ui=(localStorage.getItem('UserId')||'').replace(/^"|"$/g,'');
  var at=tk&&tk.length>100?tk:t2&&t2.length>100?t2:null;
  if(!at||!ui){alert('Token non trouve!');return}

  // Config
  var CES=['Ben Daubin','Sacha Villa','Sophie MACE'];
  var FR={'Pearl White':'Blanc perle','Diamond Black':'Noir Diamant','Stealth Grey':'Gris Stealth','Midnight Silver Metallic':'Gris Nuit','Red Multi-Coat':'Rouge','Ultra Red':'Rouge Ultra','Quicksilver':'Quicksilver','Glacier Blue':'Bleu Glacier','Frost Blue':'Bleu Givre','Midnight Cherry Red':'Rouge Cerise','Marine Blue':'Bleu Marine'};
  var now=new Date(),tmr=new Date(Date.now()+864e5);
  var fD=function(d){return d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})};
  var iD=function(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};

  var dates=[];for(var di=0;di<10&&dates.length<7;di++){var dd=new Date(Date.now()+di*864e5);if(dd.getDay()===0)continue;var lbl=di===0?'Aujourd\'hui':di===1?'Demain':'J+'+di;dates.push('<option value="'+iD(dd)+'">'+lbl+' - '+fD(dd)+'</option>')}

  // Open new tab and write clean HTML
  var w=window.open('','_blank');
  if(!w){alert('Popup bloque!');return}

  w.document.open();
  w.document.write('<!DOCTYPE html><html><head><meta charset="utf-8"><title>Tesla Delivery Hub</title>'
  +'<style>'
  +'*{box-sizing:border-box;margin:0;padding:0}'
  +'@font-face{font-family:UST;font-weight:400;font-display:swap;src:url(https://digitalassets.tesla.com/tesla-design-system/raw/upload/static/fonts/universal-sans-2/web/text/Universal-Sans-Text-Regular.woff2) format(woff2)}'
  +'@font-face{font-family:UST;font-weight:500;font-display:swap;src:url(https://digitalassets.tesla.com/tesla-design-system/raw/upload/static/fonts/universal-sans-2/web/text/Universal-Sans-Text-Medium.woff2) format(woff2)}'
  +'@font-face{font-family:UST;font-weight:700;font-display:swap;src:url(https://digitalassets.tesla.com/tesla-design-system/raw/upload/static/fonts/universal-sans-2/web/text/Universal-Sans-Text-Bold.woff2) format(woff2)}'
  +'@font-face{font-family:USD;font-weight:500;font-display:swap;src:url(https://digitalassets.tesla.com/tesla-design-system/raw/upload/static/fonts/universal-sans-2/web/display/Universal-Sans-Display-Medium.woff2) format(woff2)}'
  +'body{font-family:UST,-apple-system,BlinkMacSystemFont,sans-serif;color:#393c41;background:#fff;font-size:14px;line-height:1.5}'
  +'.hdr{height:52px;border-bottom:1px solid #e5e5e5;display:flex;align-items:center;padding:0 16px;justify-content:space-between}'
  +'.topfix{position:sticky;top:0;background:#fff;z-index:10;border-bottom:1px solid #e5e5e5}'
  +'.hdr .logo{font-size:18px;font-weight:600;letter-spacing:3px;color:#171a20}'
  +'.hdr .sep{margin:0 14px;color:#ccc}'
  +'.hdr .app{font-size:15px;color:#5c5e62}'
  +'.hdr .ri{margin-left:auto;font-size:14px;color:#5c5e62}'
  +'.ttl{padding:20px 16px 8px;font-size:20px;font-weight:500;color:#171a20;font-family:USD,UST,sans-serif}'
  +'.bar{padding:12px 16px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}'
  +'.pill{padding:6px 16px;border-radius:4px;border:1px solid #d0d0d0;background:#fff;cursor:pointer;font-size:13px;color:#5c5e62;font-family:inherit}'
  +'.pill:hover{background:#f5f5f5}'
  +'.pill.on{background:#171a20;color:#fff;border-color:#171a20}'
  +'.s2{width:1px;height:28px;background:#e0e0e0;margin:0 10px;display:inline-block}'
  +'select{padding:6px 12px;border:1px solid #d0d0d0;border-radius:4px;font-size:13px;font-family:inherit;color:#333}'
  +'.btn{padding:6px 16px;border-radius:4px;border:1px solid #d0d0d0;font-size:13px;font-family:inherit;font-weight:500;cursor:pointer;background:#f5f5f5;color:#393c41}'
  +'.bp{background:#f5f5f5;color:#393c41;border:1px solid #d0d0d0}.bp:hover,.bk:hover{background:#e8e8e8}'
  +'.bk{background:#f5f5f5;color:#393c41;border:1px solid #d0d0d0}'
  +'.sts{margin-left:auto;display:flex;gap:0;border:1px solid #e5e5e5;border-radius:8px;overflow:hidden}'
  +'.stat-click{cursor:pointer;padding:8px 16px;border-right:1px solid #e5e5e5;text-align:center;min-width:70px;transition:background .15s}'
  +'.stat-click:last-child{border-right:none}'
  +'.stat-click:hover{background:#f5f5f5}'
  +'.sn{font-size:22px;font-weight:500;text-align:center;color:#171a20}'
  +'.sn.green{color:#28a745}'
  +'.sn.red{color:#dc3545}'
  +'.sl{font-size:9px;text-transform:uppercase;letter-spacing:1.5px;color:#999;text-align:center;margin-top:2px}'
  +'.stat-click{cursor:pointer}.stat-click:hover .sn{color:#3e6ae1}'
  +'.wrp{padding:0 16px 24px}'
  +'table{width:100%;border-collapse:separate;border-spacing:0}'
  +'th{padding:12px 12px;text-align:left;font-size:12px;color:#393c41;font-weight:500;border-bottom:1px solid #f4f4f4;cursor:pointer;user-select:none;line-height:20px}'
  +'th:hover{color:#171a20}'
  +'td{padding:10px 12px;font-size:13px;border-bottom:1px solid #f4f4f4;vertical-align:middle;color:#393c41;line-height:20px;height:49px}'
  +'tr:hover td{background:#fafafa}'
  +'tr.w td{background:#fef5f5}'
  +'.ck{width:16px;height:16px;cursor:pointer;-webkit-appearance:none;appearance:none;border:1.5px solid #bbb;border-radius:2px;background:#fff;position:relative;vertical-align:middle}'
  +'.ck:checked{background:#fff;border-color:#393c41}'
  +'.ck:checked::after{content:"";position:absolute;left:4px;top:1px;width:4px;height:8px;border:solid #393c41;border-width:0 2px 2px 0;transform:rotate(45deg)}'
  +'.badge{display:inline-block;padding:5px 14px;border-radius:4px;font-size:13px;font-weight:600}'
  +'.badge.cash{background:#e6f4ea;color:#1e7e34}'
  +'.badge.leasing{background:#e3f2fd;color:#1565c0}'
  +'.badge.credit{background:#ede7f6;color:#6a1b9a}'
  +'.badge.lld{background:#fff8e1;color:#f57f17}'
  +'.badge.ent{background:#eceff1;color:#37474f}'
  +'.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:7px}'
  +'.dg{background:#28a745}.dr{background:#dc3545}.do{background:#f0ad4e}'
  +'.nm{font-weight:600;color:#171a20;font-size:15px;white-space:nowrap}'
  +'.tm{font-size:17px;font-weight:500;color:#171a20}'
  +'.pl{font-family:SFMono-Regular,Consolas,monospace;font-weight:600;font-size:15px}'
  +'.rn{font-size:12px;color:#aaa;margin-top:3px}'
  +'.sub{font-size:13px;color:#888}'
  +'.ld{text-align:center;padding:100px;font-size:16px;color:#999}'
  +'.spin{display:inline-block;width:24px;height:24px;border:3px solid #eee;border-top-color:#171a20;border-radius:50%;animation:s .6s linear infinite;margin-right:12px;vertical-align:middle}'
  +'@keyframes s{to{transform:rotate(360deg)}}'
  +'.ldbar{width:200px;height:4px;background:#eee;border-radius:2px;margin:20px auto;overflow:hidden}'
  +'.ldbar::after{content:"";display:block;width:60px;height:4px;background:#171a20;border-radius:2px;animation:ldb 1s ease-in-out infinite}'
  +'@keyframes ldb{0%{transform:translateX(-60px)}100%{transform:translateX(200px)}}'
  +'.fi{width:100%;padding:6px 10px;border:1px solid #ddd;border-radius:4px;font-size:13px;font-family:inherit;color:#555;outline:none}'
  +'.fi:focus{border-color:#999}'
  +'</style></head><body>'
  +'<div class="topfix">'
  +'<div class="hdr"><div style="display:flex;align-items:center;gap:14px;flex-shrink:0"><svg width="32" height="32" viewBox="0 0 160 160" fill="#171a20"><path d="m80 129.8 14-78.7c13.3 0 17.5 1.5 18.1 7.4 0 0 8.9-3.3 13.5-10.1-17.6-8.1-35.3-8.5-35.3-8.5L80 52.5 69.7 39.9s-17.7.4-35.3 8.5c4.5 6.8 13.5 10.1 13.5 10.1.6-6 4.8-7.4 18.1-7.4z"/><path d="M80 36.3c14.2-.1 30.5 2.2 47.2 9.5 2.2-4 2.8-5.8 2.8-5.8-18.2-7.3-35.3-9.7-50-9.8-14.7.1-31.8 2.5-50 9.8 0 0 .8 2.2 2.8 5.8 16.7-7.3 33-9.6 47.2-9.5"/></svg><span class="sep">|</span><span class="app">Delivery Hub</span></div><div style="flex:1;display:flex;justify-content:center"><input type="text" id="srch" placeholder="Search by VIN, RN, LP or Name" style="width:100%;max-width:500px;padding:10px 16px;border:1px solid #d0d0d0;border-radius:8px;font-size:14px;font-family:inherit;color:#333;outline:none"></div><span class="ri">Ben Daubin</span></div>'
  +'<div class="ttl">Delivery Dashboard</div>'
  +'<div class="bar">'
  +'<button class="pill on" onclick="F(\'all\')">Tous</button>'
  +CES.map(function(c){return'<button class="pill" onclick="F(\''+c+'\')">'+c.split(' ')[0]+'</button>'}).join('')
  +'<span class="s2"></span>'
  +'<select id="dt">'+dates.join('')+'</select>'
  +'<button class="btn bp" onclick="L()">Charger</button>'
  +'<button class="btn bk" id="gn" style="display:none" onclick="G()">Generer PDFs</button>'
  +'<button class="btn" id="disp" style="display:none;background:#171a20;color:#fff;border:none" onclick="DISPATCH()">Dispatcher</button>'
  +'<div class="sts"><div class="stat-click" onclick="SF(\'all\')"><div class="sn" id="sT">-</div><div class="sl">Livraisons</div></div>'
  +'<div class="stat-click" onclick="SF(\'ok\')"><div class="sn green" id="sO">-</div><div class="sl" style="color:#28a745">Pretes</div></div>'
  +'<div class="stat-click" onclick="SF(\'al\')"><div class="sn red" id="sA">-</div><div class="sl" style="color:#dc3545">Alertes</div></div></div>'
  +'</div>'
  +'</div>'
  +'<div class="wrp"><div class="ld" id="lg" style="display:none"><div style="text-align:center;padding:80px"><div class="ldbar"></div><div style="font-size:14px;color:#999;margin-top:16px">Chargement des livraisons...</div></div></div>'
  +'<table id="tbl" style="display:none"><thead><tr><th style="width:44px"><input type="checkbox" class="ck" id="sa" onchange="SA(this)"/></th>'
  +'<th style="cursor:pointer;width:70px" onclick="S(\'t\')">Heure</th><th style="cursor:pointer;width:16%" onclick="S(\'name\')">Client</th><th style="width:12%">RN</th><th style="cursor:pointer;width:9%" onclick="S(\'model\')">Vehicule</th><th style="cursor:pointer;width:10%" onclick="S(\'plate\')">Plaque</th><th style="width:8%">Paiement</th><th style="width:10%">Trade-In</th><th style="width:8%">OTG</th><th style="width:8%">Assurance</th>'
  +'</tr></thead><tbody id="tb"></tbody></table><div id="trec" style="padding:20px 20px;font-size:16px;color:#393c41;font-weight:600"></div></div>'
  +'<script>'
  +'var AUTH={token:"Bearer '+at.replace(/"/g,'\\"')+'",userId:"'+ui+'"};'
  +'var BASE="https://mytdeliveryopsapi.tesla.com/api";'
  +'var CFG={trtId:28498,cc:"FR"};'
  +'var CES='+JSON.stringify(CES)+';'
  +'var FR='+JSON.stringify(FR)+';'
  +'var tr=function(s){return FR[s]||s};'
  +'var pT=function(t){return{CASH:"CASH",TESLA_LEASING:"LEASING",TESLA_LENDING:"CREDIT",THIRD_PARTY_LEASING:"LLD TIERS"}[t]||t};'
  +'var pC=function(t){return{CASH:"cash",TESLA_LEASING:"leasing",TESLA_LENDING:"credit",THIRD_PARTY_LEASING:"lld"}[t]||"ent"};'
  +'var DATA=[];'
  +'function F(f){document.querySelectorAll(".pill").forEach(function(p){p.classList.remove("on")});event.target.classList.add("on");document.querySelectorAll("#tb tr").forEach(function(r){if(f==="all"){r.style.display="";return}r.style.display=(r.dataset.host||"").toLowerCase().indexOf(f.split(" ")[0].toLowerCase())>=0?"":"none"});US();TR()}'
  +'function SA(el){document.querySelectorAll(".rc").forEach(function(c){if(c.closest("tr").style.display!=="none")c.checked=el.checked})}'
  +'async function L(){'
  +'var lg=document.getElementById("lg"),tbl=document.getElementById("tbl"),tb=document.getElementById("tb");'
  +'lg.style.display="";tbl.style.display="none";lg.innerHTML=\'<div style="text-align:center;padding:80px"><div class="ldbar"></div><div style="font-size:14px;color:#999;margin-top:16px">Chargement des livraisons...</div></div>\';'
  +'var h={"Authorization":AUTH.token,"Content-Type":"application/json","userid":AUTH.userId};'
  +'var ds=document.getElementById("dt").value;'
  +'try{'
  +'var dash=await fetch(BASE+"/deliveryops/Customers/Dashboard",{method:"POST",headers:h,body:JSON.stringify({fromDeliveryDate:ds,trtId:CFG.trtId,customerHasNoHost:false,skip:0,take:200,fromTime:"00:00",toTime:"23:59",countryCode:CFG.cc,onlyMyLocation:true,sort:{},stage:[],status:[],deliveryType:[],paperwork:[],customerDeliveryStatus:[],inboundStatus:[],VehicleTypes:[],pdcFilter:[],dmvDocumentStages:[]})}).then(function(r){return r.json()});'
  +'var dm={};dash.Data.forEach(function(d){dm[d.ReferenceNumber]=d});var rns=Object.keys(dm);'
  +'if(!rns.length){lg.innerHTML="Aucune livraison.";return}'
  +'var adv=await fetch(BASE+"/advisor/Dashboard?isSidePanelFullScreen=true",{method:"POST",headers:h,body:JSON.stringify({condition:"and",rules:[{condition:"and",ReferenceNumbers:rns,Countries:[]}],Skip:0,Take:200,SortOrder:[],SelectedColumns:[]})}).then(function(r){return r.json()});'
  +'var tiC=adv.Data.Dashboard.filter(function(a){return a.TradeInActionStatus==="COMPLETE_TRADE_IN"});'
  +'var tiR={};await Promise.all(tiC.map(function(a){return fetch(BASE+"/widget/GetTradeInWidgetInfo?referenceNumber="+a.ReferenceNumber+"&vehicleMapId="+a.VehicleMapId+"&deliveryState="+encodeURIComponent(a.DeliveryState||""),{headers:h}).then(function(r){return r.json()}).then(function(j){if(j.Data)tiR[a.ReferenceNumber]={ms:j.Data.AcquisitionMilestone||""}}).catch(function(){})}));'
  +'DATA=adv.Data.Dashboard.map(function(a){var d=dm[a.ReferenceNumber]||{};var dt=d.ScheduledDeliveryStartDateString||"";var t="?",m=dt.match(/(\\d{1,2}):(\\d{2})\\s*(AM|PM)/i);if(m){var hr=parseInt(m[1]);if(m[3].toUpperCase()==="PM"&&hr<12)hr+=12;if(m[3].toUpperCase()==="AM"&&hr===12)hr=0;t=String(hr).padStart(2,"0")+":"+m[2]}var hp=!!(a.LicensePlate&&a.LicensePlate.trim()&&a.LicensePlate.indexOf("-")>=0);var io=a.InsuranceActionStatus==="COMPLETE";var otg=a.VehicleStage==="Finished Goods"||a.VehicleStage==="Arrived at VRL"||(a.VehicleStage&&a.VehicleStage.indexOf("Arrived")>=0);var amtOk=a.AmountDueActionStatus==="Yes"||a.PaymentMethodActionStatus==="COMPLETE";var al=[];if(!hp)al.push("P");if(!otg)al.push("O");if(!amtOk)al.push("$");var r=tiR[a.ReferenceNumber];var tms=r?r.ms:"";if(tms.indexOf(" - ")>=0)tms=tms.split(" - ")[0];var rs="En attente";var clientName=a.CustomerName;var di=a.DriverInfo;if(a.IsEnterpriseOrder&&di&&di.first_name)clientName=di.first_name+" "+di.last_name+" ("+a.CustomerName+")";return{rn:a.ReferenceNumber,name:clientName,t:t,model:a.VehicleModel,color:tr(a.VehicleColor||""),plate:(a.LicensePlate||"").trim(),regSt:rs,host:d.HostName||"?",b2b:a.IsEnterpriseOrder,hp:hp,io:io,otg:otg,vs:a.VehicleStage||"",al:al,tims:tms,amtOk:amtOk}}).sort(function(a,b){return a.t.localeCompare(b.t)});'
  +'var out="";for(var i=0;i<DATA.length;i++){var d=DATA[i];out+="<tr class=\\""+(d.al.length?"w":"")+"\\" data-host=\\""+d.host+"\\"><td><input type=checkbox class=\\"ck rc\\" data-i="+i+" "+(d.al.length===0?"checked":"")+"></td><td><span class=tm>"+d.t+"</span></td><td><span class=nm>"+d.name+"</span></td><td><a href=\\"https://dro.tesla.com/advisor?sidepanel_fullscreen=yes&rn="+d.rn+"\\" target=_blank style=\\"color:#3e6ae1;text-decoration:none;font-size:13px\\">"+d.rn+"</a></td><td>"+d.model+"</td><td>"+(d.hp?"<span class=pl>"+d.plate+"</span>":"<span style=color:#888;font-size:13px>"+(d.regSt==="COMPLETE"?"Completed":d.regSt==="NOT_STARTED"?"Not Started":d.regSt==="INCOMPLETE"?"In Progress":d.regSt||"N/A")+"</span>")+"</td><td>"+(d.amtOk?"<span class=\\"dot dg\\"></span>OK":"<span class=\\"dot dr\\"></span>Non")+"</td><td>"+(d.tims?"<span class=\\"dot dg\\"></span>"+d.tims:"<span style=color:#ccc>Non</span>")+"</td><td>"+(d.otg?"<span class=\\"dot dg\\"></span>Oui":"<span class=\\"dot do\\"></span><span class=sub>"+(d.vs||"Non")+"</span>")+"</td><td>"+(d.io?"<span class=\\"dot dg\\"></span>OK":"<span style=color:#999>Non</span>")+"</td></tr>"}'
  +'tb.innerHTML=out;'
  +'var ok=DATA.filter(function(d){return d.al.length===0}).length;'
  +'document.getElementById("sT").textContent=DATA.length;'
  +'document.getElementById("sO").textContent=ok;'
  +'document.getElementById("sA").textContent=DATA.length-ok;'
  +'lg.style.display="none";tbl.style.display="";document.getElementById("gn").style.display="";document.getElementById("disp").style.display="";TR();'
  +'document.getElementById("sa").checked=true;'
  +'}catch(err){lg.innerHTML="Erreur: "+err.message}}'
  +'function G(){var c=[];document.querySelectorAll(".rc:checked").forEach(function(el){var tr=el.closest("tr");if(tr&&tr.style.display!=="none"){var i=parseInt(el.dataset.i);if(DATA[i])c.push(DATA[i])}});if(!c.length){alert("Aucune livraison!");return}alert("Generation de "+c.length+" pages de garde...")}'
  +'async function DISPATCH(){var hosts=[{name:"Ben Daubin",id:"428058"},{name:"Sacha Villa",id:"399921"},{name:"Sophie MACE",id:"444287"}];var items=DATA;if(!items.length){alert("Aucune livraison a dispatcher!");return}var conf=confirm("Dispatcher "+items.length+" livraisons entre "+hosts.map(function(h){return h.name}).join(", ")+"?");if(!conf)return;var btn=document.getElementById("disp");btn.textContent="Dispatch en cours...";btn.disabled=true;var ok=0,fail=0;for(var i=0;i<items.length;i++){var d=items[i];var host=hosts[i%hosts.length];try{var r=await fetch(AUTH.token?BASE+"/deliveryops/Customers/UpdateHost?referenceNumber="+d.rn+"&value="+host.id:BASE+"/Customers/UpdateHost?referenceNumber="+d.rn+"&value="+host.id,{method:"POST",headers:{"Authorization":AUTH.token,"Content-Type":"application/json","userid":AUTH.userId}});if(r.ok)ok++;else fail++}catch(e){fail++}}btn.textContent="Dispatcher";btn.disabled=false;alert("Dispatch termine!\\n"+ok+" OK / "+fail+" erreurs\\n\\nBen: "+Math.ceil(items.length/3)+" | Sacha: "+Math.ceil(items.length/3)+" | Sophie: "+Math.floor(items.length/3))}'
  +'var sortDir={};function S(k){sortDir[k]=!sortDir[k];DATA.sort(function(a,b){var v=sortDir[k]?1:-1;return(a[k]||"").toString().localeCompare((b[k]||"").toString())*v});R()}'
  +'function R(){var tb=document.getElementById("tb");var out="";for(var i=0;i<DATA.length;i++){var d=DATA[i];out+="<tr class=\\""+(d.al.length?"w":"")+"\\" data-host=\\""+d.host+"\\"><td><input type=checkbox class=\\"ck rc\\" data-i="+i+" "+(d.al.length===0?"checked":"")+"></td><td><span class=tm>"+d.t+"</span></td><td><span class=nm>"+d.name+"</span></td><td><a href=\\"https://dro.tesla.com/advisor?sidepanel_fullscreen=yes&rn="+d.rn+"\\" target=_blank style=\\"color:#3e6ae1;text-decoration:none;font-size:13px\\">"+d.rn+"</a></td><td>"+d.model+"</td><td>"+(d.hp?"<span class=pl>"+d.plate+"</span>":"<span style=color:#888;font-size:13px>"+(d.regSt==="COMPLETE"?"Completed":d.regSt==="NOT_STARTED"?"Not Started":d.regSt==="INCOMPLETE"?"In Progress":d.regSt||"N/A")+"</span>")+"</td><td>"+(d.amtOk?"<span class=\\"dot dg\\"></span>OK":"<span class=\\"dot dr\\"></span>Non")+"</td><td>"+(d.tims?"<span class=\\"dot dg\\"></span>"+d.tims:"<span style=color:#ccc>Non</span>")+"</td><td>"+(d.otg?"<span class=\\"dot dg\\"></span>Oui":"<span class=\\"dot do\\"></span><span class=sub>"+(d.vs||"Non")+"</span>")+"</td><td>"+(d.io?"<span class=\\"dot dg\\"></span>OK":"<span style=color:#999>Non</span>")+"</td></tr>"}tb.innerHTML=out}'
  +'document.getElementById("srch").oninput=function(){var q=this.value.toLowerCase();document.querySelectorAll("#tb tr").forEach(function(r){r.style.display=r.textContent.toLowerCase().indexOf(q)>=0?"":"none"})};'
  +'function SF(t){var activeHost="";document.querySelectorAll(".pill").forEach(function(p){if(p.classList.contains("on"))activeHost=p.textContent});document.querySelectorAll("#tb tr").forEach(function(r){var hostMatch=activeHost==="Tous"||!activeHost||(r.dataset.host||"").toLowerCase().indexOf(activeHost.toLowerCase())>=0;if(!hostMatch){r.style.display="none";return}if(t==="all"){r.style.display=""}else if(t==="ok"){r.style.display=r.classList.contains("w")?"none":""}else{r.style.display=r.classList.contains("w")?"":"none"}});TR()};'
  +'function TR(){var v=0;document.querySelectorAll("#tb tr").forEach(function(r){if(r.style.display!=="none")v++});document.getElementById("trec").textContent="Total Records: "+v};function US(){var tot=0,ok=0,al=0;document.querySelectorAll("#tb tr").forEach(function(r){if(r.style.display==="none")return;tot++;if(r.classList.contains("w"))al++;else ok++});document.getElementById("sT").textContent=tot;document.getElementById("sO").textContent=ok;document.getElementById("sA").textContent=al};'
  +'</scr'+'ipt></body></html>');
  w.document.close();
})();
